### ISSUE TITLE
Update setup guide to support ubuntu

### ISSUE THREAD

**Issue by seokho-son** [m-cmp/mc-cost-optimizer#8]
## 기본 셋업 가이드 업데이트

- [x] 안녕하세요. 해당 프로젝트의 기본 셋업 가이드를 하기 OS로 제공 가능하신지 문의 드립니다.
- Linux (recommended: Ubuntu 22.04)

사유: M-CMP 프로젝트 및 Cloud-Barista 차원에서 해당 OS에서는 기본 동작할 수 있게 하려고 합니다. 
(현재 대부분의 저장소가 Ubuntu 를 기준으로 하고 있음)

## Dockerfile, Docker-compose 등 제공

- [x] 추가적으로 쉬운 구동을 위해서 dockerfile 제공, docker-compose 로 구동 방식 제공 등이 포함되어야 할 것 같습니다.

## 사용 가이드 추가

- [x] 셋업 후에, 해당 프로그램을 어떻게 사용하는지도 간략하게 가이드가 있으면 좋을 것 같습니다. (화면 캡쳐, gif, 영상 등 무관)

## 라이선스 관련 사항

- [x] 저장소에 Apache 2.0 으로 라이선스 고지문(파일) 추가 요청 드립니다.
- [x] 현재 사용하신 오픈소스 및 pkg 를 확인하셔서, Apache 2.0 에 호환되지 않는 라이선스 활용은 모드 제거해야 합니다. 메인테이너께서 확인해주셔야 합니다. (예를 들면, GPL 2.0은 Apache 2.0에 충돌하므로 활용 불가합니다.)

**Comment by seokho-son** [comment]
docker compose up 을 통해서, 서버 구동되는 것을 확인하였습니다. :)

![image](https://github.com/user-attachments/assets/9a608a1e-9cb0-4cd7-8979-57c80197431f)

![image](https://github.com/user-attachments/assets/0f4d4fc2-5dff-4d48-bda9-b9a9eb35c347)

**Comment by seokho-son** [comment]
@BSjaeyoung-kim docker compose 로 구동시, 하기 컨테이너들이 계속 재시작되는 문제가 있었습니다. 참고하시기 바랄게요. ^^ 

GCP: e2-standard-4 (CPU:4, MEM: 16GiB)
OS: Ubuntu22.04

- mc-cost-optimizer-costcollector-1
- mc-cost-optimizer-costprocessor-1
- mc-cost-optimizer-alarmservice-1

![image](https://github.com/user-attachments/assets/d14a026d-41cf-4567-8345-c263a4a8556d)


```
cb-user@ns01-mc-cost-g1-1-cqk9f8rq10m9htb48ji0:~/mc-cost-optimizer$ sudo docker events
2024-07-30T08:06:22.112013758Z network disconnect 3b523b8627a31496888c3a0e538ec13dc845c712d738a20185c1fd12ca76b115 (container=4667b46bda579f742b8005822a7011b8372526ad9ad966e4605104bdba83e05e, name=mc-cost-optimizer_mcmp_cost_network, type=bridge)
2024-07-30T08:06:22.142512626Z container die 4667b46bda579f742b8005822a7011b8372526ad9ad966e4605104bdba83e05e (com.docker.compose.config-hash=9bf8285c3179e97c1f3318e08ac1be15d987fe102ede7950cbf76cfad35db44a, com.docker.compose.container-number=1, com.docker.compose.depends_on=, com.docker.compose.image=sha256:0f7c935c49f05e7badd7c33b9e6a4302098a9856409b135c42dde203b25f8728, com.docker.compose.oneoff=False, com.docker.compose.project=mc-cost-optimizer, com.docker.compose.project.config_files=/home/cb-user/mc-cost-optimizer/docker-compose.yml, com.docker.compose.project.working_dir=/home/cb-user/mc-cost-optimizer, com.docker.compose.service=costprocessor, com.docker.compose.version=2.29.1, execDuration=14, exitCode=1, image=mc-cost-optimizer-costprocessor, name=mc-cost-optimizer-costprocessor-1)
2024-07-30T08:06:22.210157510Z network connect 3b523b8627a31496888c3a0e538ec13dc845c712d738a20185c1fd12ca76b115 (container=4667b46bda579f742b8005822a7011b8372526ad9ad966e4605104bdba83e05e, name=mc-cost-optimizer_mcmp_cost_network, type=bridge)
2024-07-30T08:06:22.458682011Z container start 4667b46bda579f742b8005822a7011b8372526ad9ad966e4605104bdba83e05e (com.docker.compose.config-hash=9bf8285c3179e97c1f3318e08ac1be15d987fe102ede7950cbf76cfad35db44a, com.docker.compose.container-number=1, com.docker.compose.depends_on=, com.docker.compose.image=sha256:0f7c935c49f05e7badd7c33b9e6a4302098a9856409b135c42dde203b25f8728, com.docker.compose.oneoff=False, com.docker.compose.project=mc-cost-optimizer, com.docker.compose.project.config_files=/home/cb-user/mc-cost-optimizer/docker-compose.yml, com.docker.compose.project.working_dir=/home/cb-user/mc-cost-optimizer, com.docker.compose.service=costprocessor, com.docker.compose.version=2.29.1, image=mc-cost-optimizer-costprocessor, name=mc-cost-optimizer-costprocessor-1)
2024-07-30T08:06:22.463038344Z container attach 4667b46bda579f742b8005822a7011b8372526ad9ad966e4605104bdba83e05e (com.docker.compose.config-hash=9bf8285c3179e97c1f3318e08ac1be15d987fe102ede7950cbf76cfad35db44a, com.docker.compose.container-number=1, com.docker.compose.depends_on=, com.docker.compose.image=sha256:0f7c935c49f05e7badd7c33b9e6a4302098a9856409b135c42dde203b25f8728, com.docker.compose.oneoff=False, com.docker.compose.project=mc-cost-optimizer, com.docker.compose.project.config_files=/home/cb-user/mc-cost-optimizer/docker-compose.yml, com.docker.compose.project.working_dir=/home/cb-user/mc-cost-optimizer, com.docker.compose.service=costprocessor, com.docker.compose.version=2.29.1, image=mc-cost-optimizer-costprocessor, name=mc-cost-optimizer-costprocessor-1)
2024-07-30T08:06:25.102014739Z network disconnect 3b523b8627a31496888c3a0e538ec13dc845c712d738a20185c1fd12ca76b115 (container=8148146246e73535506e2da5ef9e7e087ef6056439c49b8b0546d1a744a8de6f, name=mc-cost-optimizer_mcmp_cost_network, type=bridge)
```

```
cb-user@ns01-mc-cost-g1-1-cqk9f8rq10m9htb48ji0:~/mc-cost-optimizer$ sudo docker compose ps
WARN[0000] /home/cb-user/mc-cost-optimizer/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
NAME                                IMAGE                             COMMAND                  SERVICE         CREATED          STATUS                                  PORTS
mc-cost-optimizer-alarmservice-1    mc-cost-optimizer-alarmservice    "java -jar app.jar"      alarmservice    24 minutes ago   Restarting (1) Less than a second ago   
mc-cost-optimizer-be-1              mc-cost-optimizer-be              "java -jar app.jar"      be              24 minutes ago   Up 24 minutes                           0.0.0.0:9090->9090/tcp, :::9090->9090/tcp
mc-cost-optimizer-costcollector-1   mc-cost-optimizer-costcollector   "java -jar app.jar"      costcollector   24 minutes ago   Up 9 seconds                            0.0.0.0:8081->8081/tcp, :::8081->8081/tcp
mc-cost-optimizer-costprocessor-1   mc-cost-optimizer-costprocessor   "java -jar app.jar"      costprocessor   24 minutes ago   Up 2 seconds                            0.0.0.0:8082->8082/tcp, :::8082->8082/tcp
mc-cost-optimizer-costselector-1    mc-cost-optimizer-costselector    "java -jar app.jar"      costselector    24 minutes ago   Up 24 minutes                           0.0.0.0:8083->8083/tcp, :::8083->8083/tcp
mc-cost-optimizer-fe-1              mc-cost-optimizer-fe              "/docker-entrypoint.…"   fe              24 minutes ago   Up 24 minutes                           0.0.0.0:8080->80/tcp, :::8080->80/tcp
```

```
costprocessor-1  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
costprocessor-1  |      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
costprocessor-1  |      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
costprocessor-1  |      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
costprocessor-1  |      at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
costprocessor-1  |      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
costprocessor-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:165) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:88) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:829) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      ... 65 common frames omitted
costprocessor-1  | Caused by: java.net.UnknownHostException: host.docker.internal
costprocessor-1  |      at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801) ~[na:na]
costprocessor-1  |      at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[na:na]
costprocessor-1  |      at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367) ~[na:na]
costprocessor-1  |      at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301) ~[na:na]
costprocessor-1  |      at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:130) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:62) ~[mysql-connector-j-8.3.0.jar!/:8.3.0]
costprocessor-1  |      ... 67 common frames omitted
```

**Comment by BSjaeyoung-kim** [comment]
@seokho-son 로그와 화면 캡쳐로만 보았을때, 아마도 DB 연결이 현재 안된것으로 보여집니다.
DB를 docker image로 전달하려고 했는데, 현재 init query가 정상적으로 동작을 안해서, 로컬 DB를 바라보도록 되어있습니다.
테스트를 위해 개별적으로 테스트 DB 경로를 안내드리겠습니다

**Comment by seokho-son** [comment]
- 테스트를 위해 개별적으로 테스트 DB 경로를 안내는 제공해주실 필요가 없습니다. :)
- 기여자 이외에, 일반 사용자가 구동할 수 있는 가이드를 부탁드릴게요!
- 해당 구동 테스트는 일단 참고만 하시면 되겠습니다.

**Comment by seokho-son** [comment]
@BSjaeyoung-kim 본 이슈는 전체 시스템 개발 일정상 다소 지연된 시급 처리 항목이라서, 빠른 대응이 필요할 것 같습니다. 참고하시기 바랍니다.

**Comment by BSjaeyoung-kim** [comment]
적어주신 이슈사항 전부 확인 완료했습니다 ㅎㅎ
